source "https://rubygems.org"

gem "jekyll", "~> 4.2.0"
gem "webrick"

gem "github-pages", group: :jekyll_plugins

group :jekyll_plugins do
  gem "jekyll-theme-primer"
  gem "jekyll-sitemap"
  gem "jekyll-feed"
  gem "jekyll-seo-tag"
  gem "faraday-retry" # Fix für den Faraday-Fehler
end
